export const flowNodeDefinitions = {
  event: {
    label: "Evento",
    description: "Inicia un flujo desde una accion de la app.",
    icon: "●",
    inputs: [],
    outputs: ["Out"],
  },
  onClick: {
    label: "Al tocar boton",
    description: "Se ejecuta cuando el usuario toca un componente.",
    icon: "●",
    inputs: [],
    outputs: ["Out"],
  },
  onLoad: {
    label: "Al cargar pantalla",
    description: "Se ejecuta cuando se abre la pantalla.",
    icon: "▣",
    inputs: [],
    outputs: ["Out"],
  },
  onChange: {
    label: "Al cambiar valor",
    description: "Se ejecuta cuando cambia el valor de un componente.",
    icon: "◇",
    inputs: [],
    outputs: ["Out"],
  },
  onSubmit: {
    label: "Al enviar formulario",
    description: "Se ejecuta cuando se envia un formulario.",
    icon: "□",
    inputs: [],
    outputs: ["Out"],
  },
  onSelectItem: {
    label: "Al seleccionar item",
    description: "Se ejecuta cuando el usuario selecciona un item.",
    icon: "●",
    inputs: [],
    outputs: ["Out"],
  },

  addToList: {
    label: "Agregar a lista",
    description: "Agrega un valor o registro a una lista visual.",
    icon: "+",
    inputs: ["In", "Dato"],
    outputs: ["Out"],
  },
  createRecord: {
    label: "Crear registro",
    description: "Guarda datos en una tabla local o Firebase.",
    icon: "▤",
    inputs: ["In", "Dato"],
    outputs: ["Exito", "Error"],
  },
  updateRecord: {
    label: "Actualizar registro",
    description: "Actualiza datos de un registro existente.",
    icon: "▤",
    inputs: ["In", "Dato"],
    outputs: ["Exito", "Error"],
  },
  deleteRecord: {
    label: "Eliminar registro",
    description: "Elimina un registro de una tabla.",
    icon: "▤",
    inputs: ["In"],
    outputs: ["Exito", "Error"],
  },
  navigateTo: {
    label: "Navegar",
    description: "Abre otra pantalla de la aplicacion.",
    icon: "→",
    inputs: ["In"],
    outputs: ["Out"],
  },
  goBack: {
    label: "Volver",
    description: "Regresa a la pantalla anterior.",
    icon: "←",
    inputs: ["In"],
    outputs: ["Out"],
  },
  showMessage: {
    label: "Mostrar mensaje",
    description: "Muestra un aviso corto al usuario.",
    icon: "!",
    inputs: ["In", "Dato"],
    outputs: ["Out"],
  },
  showDialog: {
    label: "Mostrar dialogo",
    description: "Abre una ventana con un mensaje.",
    icon: "!",
    inputs: ["In", "Dato"],
    outputs: ["Out"],
  },
  showSnackbar: {
    label: "Mostrar snackbar",
    description: "Muestra un aviso temporal en pantalla.",
    icon: "!",
    inputs: ["In", "Dato"],
    outputs: ["Out"],
  },
  openModal: {
    label: "Abrir modal",
    description: "Muestra un modal de la aplicacion.",
    icon: "▣",
    inputs: ["In"],
    outputs: ["Out"],
  },
  closeModal: {
    label: "Cerrar modal",
    description: "Cierra el modal abierto.",
    icon: "×",
    inputs: ["In"],
    outputs: ["Out"],
  },
  setVariable: {
    label: "Cambiar variable",
    description: "Guarda o cambia el valor de una variable.",
    icon: "v",
    inputs: ["In", "Dato"],
    outputs: ["Out"],
  },
  clearVariable: {
    label: "Limpiar variable",
    description: "Borra el valor guardado en una variable.",
    icon: "v",
    inputs: ["In"],
    outputs: ["Out"],
  },
  setComponentValue: {
    label: "Cambiar valor",
    description: "Cambia el valor de un componente.",
    icon: "□",
    inputs: ["In", "Dato"],
    outputs: ["Out"],
  },
  setComponentText: {
    label: "Cambiar texto",
    description: "Cambia el texto visible de un componente.",
    icon: "T",
    inputs: ["In", "Dato"],
    outputs: ["Out"],
  },
  setComponentImage: {
    label: "Cambiar imagen",
    description: "Cambia la imagen visible de un componente.",
    icon: "▧",
    inputs: ["In", "Dato"],
    outputs: ["Out"],
  },
  setComponentProperty: {
    label: "Cambiar propiedad",
    description: "Cambia una propiedad de un componente.",
    icon: "□",
    inputs: ["In", "Dato"],
    outputs: ["Out"],
  },
  showComponent: {
    label: "Mostrar componente",
    description: "Hace visible un componente oculto.",
    icon: "◉",
    inputs: ["In"],
    outputs: ["Out"],
  },
  hideComponent: {
    label: "Ocultar componente",
    description: "Oculta un componente de la pantalla.",
    icon: "○",
    inputs: ["In"],
    outputs: ["Out"],
  },
  enableComponent: {
    label: "Habilitar componente",
    description: "Permite interactuar con un componente.",
    icon: "✓",
    inputs: ["In"],
    outputs: ["Out"],
  },
  disableComponent: {
    label: "Deshabilitar componente",
    description: "Bloquea la interaccion con un componente.",
    icon: "×",
    inputs: ["In"],
    outputs: ["Out"],
  },
  clearList: {
    label: "Limpiar lista",
    description: "Borra los elementos actuales de una lista.",
    icon: "▤",
    inputs: ["In"],
    outputs: ["Out"],
  },
  clearFields: {
    label: "Limpiar input",
    description: "Vacia inputs, textareas, busquedas y selects de la pantalla actual.",
    icon: "X",
    inputs: ["In"],
    outputs: ["Out"],
  },

  ifEmpty: {
    label: "Si vacio",
    description: "Separa el flujo si el dato esta vacio.",
    icon: "?",
    inputs: ["In", "Dato"],
    outputs: ["Verdadero", "Falso"],
  },
  ifEquals: {
    label: "Si igual",
    description: "Separa el flujo si el dato coincide.",
    icon: "?",
    inputs: ["In", "Dato"],
    outputs: ["Verdadero", "Falso"],
  },
  ifGreater: {
    label: "Si mayor",
    description: "Separa el flujo si el dato es mayor que un valor.",
    icon: "?",
    inputs: ["In", "Dato"],
    outputs: ["Verdadero", "Falso"],
  },
  ifContains: {
    label: "Si contiene",
    description: "Separa el flujo si el dato contiene un texto.",
    icon: "?",
    inputs: ["In", "Dato"],
    outputs: ["Verdadero", "Falso"],
  },
  if: {
    label: "Condicion",
    description: "Condicion libre compatible con flujos anteriores.",
    icon: "?",
    inputs: ["In", "Dato"],
    outputs: ["Verdadero", "Falso"],
  },
  else: {
    label: "Si no",
    description: "Continua cuando no se cumple una condicion anterior.",
    icon: "?",
    inputs: ["In"],
    outputs: ["Out"],
  },
  switch: {
    label: "Elegir camino",
    description: "Elige una salida segun el valor de una expresion.",
    icon: "?",
    inputs: ["In", "Dato"],
    outputs: ["Verdadero", "Falso"],
  },

  getComponentValue: {
    label: "Obtener valor",
    description: "Entrega una propiedad de un componente como dato.",
    icon: "◇",
    inputs: [],
    outputs: ["Valor"],
  },
  getVariable: {
    label: "Variable",
    description: "Entrega el valor de una variable como dato.",
    icon: "v",
    inputs: [],
    outputs: ["Valor"],
  },
  getRecord: {
    label: "Registro",
    description: "Entrega un registro especifico como dato.",
    icon: "▤",
    inputs: [],
    outputs: ["Valor"],
  },
  listRecords: {
    label: "Resultado consulta",
    description: "Entrega varios registros de una tabla como dato.",
    icon: "▤",
    inputs: [],
    outputs: ["Valor"],
  },
  filterRecords: {
    label: "Resultado filtrado",
    description: "Entrega registros filtrados como dato.",
    icon: "▤",
    inputs: [],
    outputs: ["Valor"],
  },
  readList: {
    label: "Lista actual",
    description: "Entrega los datos actuales de una lista como dato.",
    icon: "▤",
    inputs: [],
    outputs: ["Valor"],
  },
  readText: {
    label: "Texto componente",
    description: "Entrega el texto visible de un componente como dato.",
    icon: "T",
    inputs: [],
    outputs: ["Valor"],
  },

  customFunction: {
    label: "Funcion personalizada",
    description: "Permite definir una funcion o accion propia.",
    icon: "{}",
    inputs: ["In"],
    outputs: ["Success", "Error"],
  },
};

export const flowNodeGroups = [
  ["Eventos", ["onLoad", "onClick", "onSelectItem", "onChange", "onSubmit"]],
  ["Acciones", ["addToList", "createRecord", "updateRecord", "deleteRecord", "navigateTo", "goBack", "showMessage", "showDialog", "showSnackbar", "openModal", "closeModal", "setVariable", "clearVariable", "setComponentValue", "setComponentText", "setComponentImage", "setComponentProperty", "showComponent", "hideComponent", "enableComponent", "disableComponent", "clearList", "clearFields"]],
  ["Condiciones", ["ifEmpty", "ifEquals", "ifGreater", "ifContains"]],
  ["Datos", ["getComponentValue", "getVariable", "getRecord", "listRecords", "filterRecords", "readList", "readText"]],
  ["Personalizado", ["customFunction"]],
];

export function getFlowNodeDefinition(type) {
  return flowNodeDefinitions[type] || {
    label: type || "Nodo",
    description: "Nodo del flujo.",
    icon: "{}",
    inputs: ["In"],
    outputs: ["Out"],
  };
}
